services:
  streaming:
    image: nginx-cs418-rtmp:latest
    container_name: docker-streaming
    ports:
      - "1935:1935"
      - "80:80"
    volumes:
      - ./config/conf.d:/etc/nginx/conf.d:ro
      - ./dist:/usr/share/nginx/html:ro
      - type: bind
        source: ./config/nginx/nginx.conf
        target:  /etc/nginx/nginx.conf
        read_only: true
    command: nginx -g 'daemon off;'